import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HeaderSection from '../components/HeaderSection'
import AboutSection from '../components/AboutSection'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stephen Plummer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderSection />
      <AboutSection/>
    </div>
  )
}
